esphome:
  name: test
  friendly_name: test
  on_boot:
    priority: 800
    then:
    #- delay: 2000 ms
    - switch.turn_on: gpio0_switch
    - switch.turn_on: gpio1_switch
    - switch.turn_on: gpio2_switch

esp8266:
  board: esp01_1m
  # restore_from_flash: true

# Enable logging
logger:
  baud_rate: 0 # Defaults to 115200. Set to 0 to disable logging via UART.



# Enable Home Assistant API
api:
  encryption:
    key: "N9sd3c4MH7fB+PIlK+A+OwzDiF3jbP6wPUx4i0Z7vu4="

ota:
  password: "059ee56eedd59043f7ce087637984459"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "fvpuwbm0Mysk"

captive_portal:
    
switch:
  - platform: gpio
    id: gpio0_switch
    pin:
      number: GPIO0
    name: "GPIO0"
    inverted: True
    restore_mode: ALWAYS_OFF

  - platform: gpio
    id: gpio2_switch
    pin: GPIO2
    name: "GPIO2"
    inverted: True
    restore_mode: ALWAYS_OFF

  - platform: gpio
    id: gpio1_switch
    pin:
      number: GPIO1
      mode: 
        output: true
    name: "GPIO1"
    inverted: True
    on_turn_on: 
      then:
        - logger.log:
            level: DEBUG
            format: 'The state of gpio1_switch is %d'
            args: ['id(gpio1_switch).state']
    restore_mode: ALWAYS_OFF

  - platform: restart
    name: "Device Restart" # optional device restart switch, change the name

#  - platform: gpio
#    pin: GPIO3
#    name: "GPIO3"    